matriz=[[0,0,0],[0,0,0]]
print(matriz)
matriz[0][0]=int(input("Ingresa elemento en [0][0] :"))
matriz[0][1]=int(input("Ingresa elemento en [0][1] :"))
matriz[0][2]=int(input("Ingresa elemento en [0][2] :"))
matriz[1][0]=int(input("Ingresa elemento en [1][0] :"))
matriz[1][1]=int(input("Ingresa elemento en [1][1] :"))
matriz[1][2]=int(input("Ingresa elemento en [1][2] :"))
print("El elemento [0][0] es:",matriz[0][0])
print("El elemento [0][1] es:",matriz[0][1])
print("El elemento [0][2] es:",matriz[0][2])
print("El elemento [1][0] es:",matriz[1][0])
print("El elemento [1][1] es:",matriz[1][1])
print("El elemento [1][2] es:",matriz[1][2])
print(matriz)
